### ISSUE TITLE
Web Search

### ISSUE THREAD

**Issue by yamsgithub** [ViDA-NYU/domain_discovery_tool#2]
1.No indicator if the pages are being downloaded
2. Cannot use "enter" key to start the search in the text box. Have to click on the search button to start the search.

**Comment by soniacq** [comment]
**1.No indicator if the pages are being downloaded**
It was added an indicator (snackbar) which tell us that the pages are being downloaded.
**2. Cannot use "enter" key to start the search in the text box.**
Done. Now, enter key is used to start the search in the text box in webQuery , seedFinder and filter by keyword searches.

**Comment by yamsgithub** [comment]
1. The snackbar is not working sometimes. Created issue #11 to track this.
2. Cannot use "enter" key to start the search in the text box.
Done
