### ISSUE TITLE
DDT stops searching after a while

### ISSUE THREAD

**Issue by kienpt** [VIDA-NYU/domain_discovery_tool#22]
So I built the model, started a crawl then searched for few queries again using both Google and Bing APIs. DDT did not return any results after these.  Following is the log. I think when I entered the query, there were other logs but I was not able to copy since DDT keeps printing new logs.

127.0.0.1 - - [23/May/2017:20:45:44] "POST /getStatus HTTP/1.1" 200 2 "http://localhost:8084/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

 Status  {} 

127.0.0.1 - - [23/May/2017:20:45:44] "POST /getStatus HTTP/1.1" 200 2 "http://localhost:8084/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

 Status  {} 

127.0.0.1 - - [23/May/2017:20:45:45] "POST /getStatus HTTP/1.1" 200 2 "http://localhost:8084/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

 Status  {} 

127.0.0.1 - - [23/May/2017:20:45:45] "POST /getStatus HTTP/1.1" 200 2 "http://localhost:8084/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

 Status  {}

**Comment by yamsgithub** [comment]
This was probably when we had Goog and Bing quota issues. I tested this scenario and do not see a problem.
