### ISSUE TITLE
DDT shows the wrong numbers in Filters > Model Tags

### ISSUE THREAD

**Issue by kienpt** [VIDA-NYU/domain_discovery_tool#23]
I clicked to "Change Domain" and chose the same domain again. In Filters > Model Tags, it shows wrong numbers. Indeed, I only labelled about 40 pages, but it showed Maybe Relevant (15), Maybe Irrelevant (462), etc.. I think it messed up with numbers from other domain.

**Comment by yamsgithub** [comment]
This was because the pages that were already predicted are included. This has been fixed with commit https://github.com/ViDA-NYU/domain_discovery_API/commit/14389aa0302d1aca6393ecfd3b96c785f33c683d
