### ISSUE TITLE
tagging pages with the filter "neutral"

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/domain_discovery_tool#31]
To identify additional relevant pages, I set the Tags filter to Neutral, and used keywords that are relevant for my target domain.

Once I select "Tag All", all snippets disappear.

While I understand that the tagged pages are no longer "Neutral", this is likely to confuse users. We should not show an empty page. We should instead display snippets for pages that are still neutral.

**Comment by yamsgithub** [comment]
This fix seems to have broken the custom tagging pages of Neutral pages. Could you please fix that.

**Comment by soniacq** [comment]
Sure. I will do it.

2017-08-04 9:56 GMT-04:00 yamsgithub <notifications@github.com>:
