### ISSUE TITLE
can't export model and crash

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/domain_discovery_tool#33]
I tried to export a model. The process failed and DDT crashed. The log is attached below.

2 suggestions:
- can we change the label in the button from Model to Export Model? (In general, we should try to make the labels more descriptive)
- can we catch this error and provide an error message to the user? As is, the application remains 'working' and unless the user checks the terminal, it is not possible to know that a problem has occurred.

**Comment by yamsgithub** [comment]
1. Label has been changed to 'Create Model'
2. Cannot reproduce this error.
