### ISSUE TITLE
loading URLs from same file fails

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/domain_discovery_tool#34]
I upload a file "test.txt" with a set of URLs. I change the file and add new URLs, and upload again -- nothing happens.

If I rename the file, the file and URLs are loaded.

Suggestion: the file I loaded had 600+ URLs; while the file is being loaded, DDT should provide some indication that it is still working on the file.

**Comment by yamsgithub** [comment]
I tested this and am able to upload by changing the same file.
