### ISSUE TITLE
tagging all pages that meet a criterion

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/domain_discovery_tool#35]
When we load URLs from file and we are sure the pages are all relevant, we should be able to tags all of them at the same time.

Right now, we are only allowed to tag one page (20 results) at a time. 

I loaded 600+ pages and now I need to go through *many* result pages to label them all.

**Comment by yamsgithub** [comment]
This is fixed by commit https://github.com/ViDA-NYU/domain_discovery_tool_react/commit/2fc4d425c67ece7e657560b61b8165f1c542a4ab
