### ISSUE TITLE
repeated results pages (suspect this is a synchronization problem)

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/domain_discovery_tool#44]
Issued a "filter" query over pages already on Elastic Search. As a click on the next page, the same results are shown over different pages (see screenshots below -- note that the page numbers change--5,6,7, but the results are the same)

![image](https://user-images.githubusercontent.com/2118982/27243574-94705564-52b0-11e7-9e9a-4cfb706305bd.png)
![image](https://user-images.githubusercontent.com/2118982/27243590-a3d1aec2-52b0-11e7-80c1-dfb376537e6e.png)
![image](https://user-images.githubusercontent.com/2118982/27243601-adb4bd8a-52b0-11e7-810c-572a0e3af7dc.png)

**Comment by yamsgithub** [comment]
SInce this was an artifact of a delayed response I now clear the old
results and wait for the new pages.

Since pagination does sorting it could be slow for larger indexes.

Thanks
Yamuna

**Comment by yamsgithub** [comment]
This was fixed.
