### ISSUE TITLE
JAVA_HOME and  make: *** No rule to make target 

### ISSUE THREAD

**Issue by nonokh** [VIDA-NYU/domain_discovery_tool#60]
I ran the make command and got two errors:

> source activate dd_api; \
pushd seeds_generator; \
mvn compile assembly:single; \
popd
~/domain_discovery_API/seeds_generator ~/domain_discovery_API
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-9-oracle/bin/java
~/domain_discovery_API
make: _*** No rule to make target_ '/home/nono/anaconda3/envs/dd_api/data/D_cbow_pdw_8B.pkl', needed by 'ranking/D_cbow_pdw_8B.pkl'.  Stop.

> 
I have java version-8 but why i it showing _java-9-oracle_ 
when i do mvn --version:

> nono@nono-Inspiron-3542:~$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: /opt/maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-32-generic", arch: "amd64", family: "unix"

> 

and how to rectify the following _*** No rule to make target_ error.

THNAK YOU.

**Comment by yamsgithub** [comment]
Is this still an issue? If not please close the issue.

**Comment by yamsgithub** [comment]
Closing issue as there was no response.
