### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by ghost** [VIDA-NYU/domain_discovery_tool#67]
Hello, @yamsgithub I want to contribute in "Domain Discovery Tool" so i designed a new logo for The "Domain Discovery Tool" Project and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

**Comment by yamsgithub** [comment]
Thanks! I don't see the logo. Also could you please let us know your interest in DDT and how you plan to use and contribute to it?

**Comment by ghost** [comment]
Hi dear @yamsgithub 
i am working on GitHub for open source programs as a freelancer and i just visit your website and check that you have no logo on your website and that's why i offer you a logo.
i am sending you some samples of logo please have a look and let me know if you like anyone
i can also change colors fonts e.t.c its just sample you need to choose any icon 
![untitled-1 copy](https://user-images.githubusercontent.com/38813945/39808651-f438d504-5398-11e8-9ab3-a8ec630a7f61.jpg)

**Comment by ghost** [comment]
Hello dear @yamsgithub have a look please check logos and let me know if you like any one?

**Comment by yamsgithub** [comment]
@waqasanwar94 thanks and couple of them could be relevant...so good effort. But unfortunately due to security reasons we cannot accept unsolicited logos and related code. We only allow use and contribution to the project itself. But thanks again for your effort.
