### ISSUE TITLE
ValueError: Empty vocabulary in _count_vocab

### ISSUE THREAD

**Issue by siatpat** [VIDA-NYU/domain_discovery_tool#70]
Hello, 

I am having the following issue when running domain discovery tool for the first time from a clean installation with docker:
- ValueError: empty vocabulary is raised in _count_vocab

See attached files
![dockerinfo](https://user-images.githubusercontent.com/5452002/50775335-2f54ed00-1296-11e9-8b7a-b2b01e746a4d.JPG)
![dockerimages](https://user-images.githubusercontent.com/5452002/50775342-354ace00-1296-11e9-89a9-a06ed60a2503.JPG)
![containers](https://user-images.githubusercontent.com/5452002/50775344-3aa81880-1296-11e9-8d7c-0d2817fdade0.JPG)
![enginebusstarted](https://user-images.githubusercontent.com/5452002/50775350-3ed43600-1296-11e9-9626-fde6ae1e2100.JPG)
![error while doing the same search with ebola as in the doc](https://user-images.githubusercontent.com/5452002/50775358-41369000-1296-11e9-92fa-7c35685408a6.JPG)

Please any help would be appreciated

Regards, 

Patrice

**Comment by iord** [comment]
Hello, I have the same problem, did you solve it?

**Comment by yamsgithub** [comment]
Do you have an empty domain? As in have you uploaded data and still see this error?

**Comment by iord** [comment]
Thank you for your interest! Yes I have the same error. I upload here same screenshots, maybe they help. Generally, it seems like it doesn't upload urls either from external file or from manual input or web search query.

![Screenshot from 2019-05-27 10-38-38](https://user-images.githubusercontent.com/29168198/58403812-44c38b80-806c-11e9-8c0c-f40ac5a29f54.png)
![Screenshot from 2019-05-27 10-27-20](https://user-images.githubusercontent.com/29168198/58403830-5442d480-806c-11e9-86e9-e5a221671351.png)

![Screenshot from 2019-05-27 10-44-26](https://user-images.githubusercontent.com/29168198/58403720-0f1ea280-806c-11e9-87d0-14708b588ac8.png)

![Screenshot from 2019-05-27 09-57-22](https://user-images.githubusercontent.com/29168198/58403256-e4801a00-806a-11e9-90f1-6d5115c249ed.png)

![Screenshot from 2019-05-27 10-02-33](https://user-images.githubusercontent.com/29168198/58403277-ef3aaf00-806a-11e9-963b-b528f59baf98.png)

![Screenshot from 2019-05-27 10-11-19](https://user-images.githubusercontent.com/29168198/58403460-63755280-806b-11e9-90ff-b1364cad8147.png)

>

**Comment by yamsgithub** [comment]
This issue should now be fixed. I have uploaded a new docker container. Please test after you do:
>>> docker pull vidanyu/ddt:latest
You should be able to upload the urls now.

**Comment by yamsgithub** [comment]
The docker was built with the wrong jdk version which caused the problem.

**Comment by iord** [comment]
Thank you very much I will try it and I will sent you feedback. I am not sure if it is meaningful but note that my problem was during the local development and not during some of background or interactive docker mode.

**Comment by yamsgithub** [comment]
Sure. In the case of local development just update both the dd api and dd tool from git. I updated the environment.yml file with the correct version of openjdk. Then rebuild both dd api and dd tool and try it. Would greatly appreciate it if you could try it out and let us know it works.

**Comment by iord** [comment]
Local development worked!! I will try it and if I have any problem I will inform you.
Thank you very much!

**Comment by yamsgithub** [comment]
Great! Thanks for informing. I will now close the ticket then. You can reopen if there is an issue.
